### ISSUE TITLE
Open Dev Terminal is a no op

### ISSUE THREAD

**Issue by jeffmaury** [crc-org/crc-extension#151]
When the menu is selected, nothing is happening.

I have this in the Podman Desktop log:

```
Error: Unknown command: crc.dev.terminal
    at W6.executeCommand (C:\Users\demo\AppData\local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:14:41998)
    at IpcMainImpl.<anonymous> (C:\Users\demo\AppData\local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:91:38747)
    at IpcMainImpl.emit (node:events:513:28)
    at i.menuItem.click (C:\Users\demo\AppData\local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:14:33918)
    at MenuItem.click (node:electron/js2c/browser_init:2:30795)
    at a._executeCommand (node:electron/js2c/browser_init:2:36191)
```

**Comment by gbraad** [comment]
Hmmmm... interesting...

**Comment by gbraad** [comment]
I have able to open the terminal:

https://github.com/crc-org/crc-extension/blob/3acf5090000385204a388d20023ab12013586951/src/dev-terminal.ts#L34

![image](https://github.com/crc-org/crc-extension/assets/1894/20eb2cdb-1475-46e1-a29c-0782eccce467)

Need more information

**Comment by jeffmaury** [comment]
Works for me with Podman Desktop 1.1.0 and extension 1.0.3
