### ISSUE TITLE
[BUG] OpenShift Local start error: Error: failed to expose port 127.0.0.1:2222

### ISSUE THREAD

**Issue by odockal** [crc-org/crc-extension#194]
### General information

  * Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)? N/A - extension does not have this option
  * Running CRC on: Laptop

## CRC version
```bash
# Put `crc version` output here
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
```

## CRC config
```bash
crc config view
- consent-telemetry                     : no
```

## Host Operating System
```bash
systeminfo

Host Name:                 DESKTOP-BDDQV3I
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Ondrej
Registered Organization:
Product ID:                00330-80000-00000-AA049
Original Install Date:     2/10/2023, 10:15:11 AM
System Boot Time:          12/14/2023, 1:48:22 PM
System Manufacturer:       LENOVO
System Model:              20LAS3NJ0U
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 10 GenuineIntel ~1910 Mhz
BIOS Version:              LENOVO N27ET29W (1.15 ), 8/8/2018
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             cs;Czech
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague
Total Physical Memory:     32,383 MB
Available Physical Memory: 25,663 MB
Virtual Memory: Max Size:  37,247 MB
Virtual Memory: Available: 30,532 MB
Virtual Memory: In Use:    6,715 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-BDDQV3I
Hotfix(s):                 19 Hotfix(s) Installed.
                           [01]: KB5032005
                           [02]: KB5028853
                           [03]: KB5011048
                           [04]: KB5011052
                           [05]: KB5012170
                           [06]: KB5015684
                           [07]: KB5020683
                           [08]: KB5033372
                           [09]: KB5014032
                           [10]: KB5016705
                           [11]: KB5023794
                           [12]: KB5025315
                           [13]: KB5026879
                           [14]: KB5028318
                           [15]: KB5028380
                           [16]: KB5029709
                           [17]: KB5031539
                           [18]: KB5032392
                           [19]: KB5032907
Network Card(s):           4 NIC(s) Installed.
                           [01]: Intel(R) Ethernet Connection (4) I219-LM
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [02]: Intel(R) Dual Band Wireless-AC 8265
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.50.1
                                 IP address(es)
                                 [01]: 192.168.50.109
                                 [02]: fe80::8b80:6dfd:d1d0:dbd3
                           [03]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Default Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.21.160.1
                                 [02]: fe80::6124:7e32:a7a9:3c7d
                           [04]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (WSL)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.23.48.1
                                 [02]: fe80::7268:395a:1d25:d24
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

### Steps to reproduce

  1. Install extension into podman desktop
  2. Install CRC via PD
  3. When asked about preset, choose openshift
  4. Let is finish, pass through the error (you needed to reboot) - ignore that, reboot machine
  5. Start PD again
  6. Initialize and start Openshift local
  7. There is an error

### Expected

Started Openshift local resource

### Actual
Error.
![openshift_local_startup_error_port_socket](https://github.com/crc-org/crc-extension/assets/19164299/66828e3f-1d12-40b9-8a03-878788e6b295)

### Logs
```
VM5:2 main ↪️ [openshift-local] Error: failed to expose port 127.0.0.1:2222 -> 192.168.127.2:22: listen tcp 127.0.0.1:2222: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

    at DaemonCommander.start (C:\Users\Ondrej\.local\share\containers\podman-desktop\plugins\quayioredhatdeveloperopenshiftlocalextension\dist\extension.js:9367:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startCrc (C:\Users\Ondrej\.local\share\containers\podman-desktop\plugins\quayioredhatdeveloperopenshiftlocalextension\dist\extension.js:25386:24)
    at async createCrcVm (C:\Users\Ondrej\.local\share\containers\podman-desktop\plugins\quayioredhatdeveloperopenshiftlocalextension\dist\extension.js:26661:24)
    at async Object.initialize (C:\Users\Ondrej\.local\share\containers\podman-desktop\plugins\quayioredhatdeveloperopenshiftlocalextension\dist\extension.js:26637:13)
    at async OK.initializeProvider (C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:53:74943)
    at async C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:345:19649
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:88640)
console.<computed> @ VM5:2
```

Before gather the logs try following if that fix your issue - No

**Comment by cfergeau** [comment]
This is the result of podman-machine and crc fighting over the same port (2222). It's tracked in https://github.com/crc-org/crc/issues/3855
