### ISSUE TITLE
[BUG] Cluster is busy when restarting microshift, fails to start back up

### ISSUE THREAD

**Issue by rostalan** [crc-org/crc-extension#210]
### General information

  * OS: Fedora 40
  * Did you run `crc setup` before starting yes
  * Running CRC on: Laptop

## CRC version
```bash
CRC version: 2.34.1+b470b5
OpenShift version: 4.15.3
Podman version: 4.4.4
```
  
## CRC status
```bash
CRC VM:          Stopped
MicroShift:      Stopped (v4.15.3)
RAM Usage:       0B of 0B
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     111.2GB
Cache Directory: /home/rostislavlan/.crc/cache
```

## CRC config
```bash
# Put `crc config view` output here
```

## Host Operating System
```bash
NAME="Fedora Linux"
VERSION="40 (Workstation Edition)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

### Steps to reproduce

  1. Open PD, resources page, set up microshift 
  2. Click restart 

### Expected
cluster restarts

### Actual
cluster stops, displays 'Error: cluster is busy'

### Logs

VM5:2 main ↪️ [openshift-local] Error: cluster is busy

    at DaemonCommander.start (/home/rostislavlan/.local/share/containers/podman-desktop/plugins/quayioredhatdeveloperopenshiftlocalextension/dist/extension.js:9367:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startCrc (/home/rostislavlan/.local/share/containers/podman-desktop/plugins/quayioredhatdeveloperopenshiftlocalextension/dist/extension.js:25386:24)
    at async Object.start (/home/rostislavlan/.local/share/containers/podman-desktop/plugins/quayioredhatdeveloperopenshiftlocalextension/dist/extension.js:26740:13)
    at async Ame.startProviderConnection (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:286:292065)
    at async /app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:338:16680
    at async /app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:336:20632
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:82796)

**Comment by odockal** [comment]
I am suspecting that this is just a result of crc daemon being "turned on" for a while. I have hit the same issue, it was also reported already, during fresh creation of microshift cluster. I just click confirmed, waited a little and all seems to be working.

**Comment by rostalan** [comment]
> I am suspecting that this is just a result of crc daemon being "turned on" for a while. I have hit the same issue, it was also reported already, during fresh creation of microshift cluster. I just click confirmed, waited a little and all seems to be working.

Does that mean the cluster starts back up for you? Mine doesn`t. Is [this](https://github.com/crc-org/crc-extension/issues/148) the issue you refer to?
