### ISSUE TITLE
[BUG] Extension is in failed state after installation via Podman Desktop

### ISSUE THREAD

**Issue by odockal** [crc-org/crc-extension#232]
### General information

  * macOS 14.5
  * Mac Mini M2 
  * CRC extension 1.3.0
  * Podman Desktop 1.11.0-next

### Steps to reproduce

  1. Download and install latest Podman Desktop (arm .dmg file) as of 1.11.0-next 
  2. Start up podman desktop, skip onboarding
  3. Open Extensions
  4. Open Catalog
  5. Install OpenShift Local
 
### Expected
Extension is installed successfully, it's state under installed extension is RUNNING

### Actual
Extension is in Failed State with error: `Expected Double quoted property name in JSON ...`

### Logs
```
Error: Expected double-quoted property name in JSON at position 98 (line 6 column 2) in "https://access.cdn.redhat.com/content/origin/files/sha256/8a/8a1bf2cfd8ba6841b30f3f9b79f733d0594e869306d125a2dfdda1fa406cab11/release-info.json?_auth_=1718655295_022c5373909342229a8adca3a2183a87"
Stack trace:
RequestError: Expected double-quoted property name in JSON at position 98 (line 6 column 2) in "https://access.cdn.redhat.com/content/origin/files/sha256/8a/8a1bf2cfd8ba6841b30f3f9b79f733d0594e869306d125a2dfdda1fa406cab11/release-info.json?_auth_=1718655295_022c5373909342229a8adca3a2183a87"
    at parseBody (/Users/podmanqe/.local/share/containers/podman-desktop/plugins/quayioredhatdeveloperopenshiftlocalextension/dist/extension.js:7764:15)
    at /Users/podmanqe/.local/share/containers/podman-desktop/plugins/quayioredhatdeveloperopenshiftlocalextension/dist/extension.js:9022:20
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CrcInstall.hasUpdate (/Users/podmanqe/.local/share/containers/podman-desktop/plugins/quayioredhatdeveloperopenshiftlocalextension/dist/extension.js:25136:31)
    at async registerCrcUpdate (/Users/podmanqe/.local/share/containers/podman-desktop/plugins/quayioredhatdeveloperopenshiftlocalextension/dist/extension.js:26607:24)
    at async activate (/Users/podmanqe/.local/share/containers/podman-desktop/plugins/quayioredhatdeveloperopenshiftlocalextension/dist/extension.js:26597:9)
    at async zle.activateExtension (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:146:61256)
    at async zle.loadExtension (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:146:50553)
    at async zle.loadExtensions (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:146:46610)
    at async Age.installFromImage (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:156:84)
    at parse (<anonymous>)
    at parseBody (/Users/podmanqe/.local/share/containers/podman-desktop/plugins/quayioredhatdeveloperopenshiftlocalextension/dist/extension.js:7757:48)
    at /Users/podmanqe/.local/share/containers/podman-desktop/plugins/quayioredhatdeveloperopenshiftlocalextension/dist/extension.js:9022:20
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CrcInstall.hasUpdate (/Users/podmanqe/.local/share/containers/podman-desktop/plugins/quayioredhatdeveloperopenshiftlocalextension/dist/extension.js:25136:31)
    at async registerCrcUpdate (/Users/podmanqe/.local/share/containers/podman-desktop/plugins/quayioredhatdeveloperopenshiftlocalextension/dist/extension.js:26607:24)
    at async activate (/Users/podmanqe/.local/share/containers/podman-desktop/plugins/quayioredhatdeveloperopenshiftlocalextension/dist/extension.js:26597:9)
    at async zle.activateExtension (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:146:61256)
    at async zle.loadExtension (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:146:50553)
    at async zle.loadExtensions (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:146:46610)

```

**Comment by dgolovin** [comment]
Also reported here https://github.com/crc-org/crc/issues/4235.

**Comment by dgolovin** [comment]
Should be fine in master branch after https://github.com/crc-org/crc-extension/issues/229 was fixed last week.

**Comment by dgolovin** [comment]
Fixed via https://github.com/crc-org/crc-extension/issues/229.
